# In netlify.toml
[build]
  functions = "netlify/functions"
  publish   = "dist"

[[redirects]]
  from  = "/api/*"
  to    = "https://api.mangadex.org/:splat"
  status = 200
  force  = true

# This is the NEW/CORRECTED redirect for the image proxy
[[redirects]]
  from  = "/image-proxy/*"  # The path your frontend will request
  to    = "/.netlify/functions/image-proxy" # This MUST point to your function path
  status = 200              # Keep as 200 for an internal rewrite
  force  = true

