[build]
  command   = "npm run build"
  publish   = "dist"

# Proxy any /api/* request to the MangaDex API
[[redirects]]
from = "/api/*"
to = "https://api.mangadex.org/:splat"
status = 200
force = true

[[redirects]]
from = "/apii/*"
to = "https://uploads.mangadex.org/:splat"
status = 200
force = true