[build]
  command   = "npm run build"
  publish   = "dist"

# Proxy any /api/* request to the MangaDex API
[[redirects]]
  from   = "/api/:splat"
  to     = "https://api.mangadex.org/:splat"
  status = 200
  force  = true